# Generated by Django 4.2.1 on 2023-05-10 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='drugs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('drugname', models.CharField(max_length=158)),
                ('state', models.CharField(max_length=158)),
                ('batch', models.DateTimeField(auto_now_add=True)),
                ('mfg', models.DateTimeField(auto_now_add=True)),
                ('packmaterial', models.CharField(max_length=158)),
                ('expirydate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='stability',
            fields=[
                ('stability_id', models.AutoField(primary_key=True, serialize=False)),
                ('stab_name', models.CharField(max_length=158)),
                ('temp', models.CharField(max_length=158)),
                ('humidity', models.CharField(max_length=158)),
                ('duration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='zone',
            fields=[
                ('zone_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=158, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='result',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('drug', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.drugs')),
                ('stability', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.stability')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.zone')),
            ],
        ),
    ]
