# Generated by Django 4.2.1 on 2023-05-24 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stability',
            name='duration',
        ),
    ]
