# Generated by Django 4.2.1 on 2023-05-26 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_stability_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugs',
            name='expirydate',
            field=models.DateField(null=True, verbose_name='Date'),
        ),
    ]
