# Generated by Django 4.2.1 on 2023-07-06 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_drugs_state_result_alert_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugs',
            name='batch',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='drugs',
            name='mfg',
            field=models.DateTimeField(),
        ),
    ]
