# Generated by Django 4.2.1 on 2023-07-06 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_drugs_mfg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drugs',
            old_name='company',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='drugs',
            old_name='drugname',
            new_name='Productname',
        ),
        migrations.AlterField(
            model_name='drugs',
            name='mfg',
            field=models.DateField(null=True, verbose_name='Date'),
        ),
    ]
