# Generated by Django 4.2.1 on 2023-07-09 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_result_alert_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stability',
            name='humidity',
        ),
        migrations.RemoveField(
            model_name='stability',
            name='temp',
        ),
        migrations.AddField(
            model_name='result',
            name='humidity',
            field=models.CharField(default='N/A', max_length=158),
        ),
        migrations.AddField(
            model_name='result',
            name='temp',
            field=models.CharField(default='N/A', max_length=158),
        ),
    ]
