# Generated by Django 4.2.5 on 2023-12-14 04:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_result_alert_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugs',
            name='mobile',
            field=models.CharField(default='', max_length=10, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(10)], verbose_name='Mobile'),
        ),
    ]
