# Generated by Django 4.2.5 on 2023-12-14 05:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_drugs_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugs',
            name='mobile',
            field=models.CharField(default='', max_length=15, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(10)], verbose_name='Mobile'),
        ),
    ]
